## Most cited publications with title keyword "database"
PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?label (COUNT(?citation) as ?cites) WHERE {
  ?publ rdf:type dblp:Publication .
  ?publ dblp:publishedInStream <https://dblp.org/streams/conf/csl> .
  ?publ dblp:yearOfPublication ?year .
  
  ?publ dblp:omid ?omid .
  ?publ rdfs:label ?label .
  ?citation rdf:type cito:Citation .
  ?citation cito:hasCitedEntity ?omid .
}
GROUP BY ?publ ?label 
ORDER BY DESC(?cites)
LIMIT 50